### ISSUE TITLE
增加健康检查脚本

### ISSUE THREAD

**Issue by pacoxu** [DaoCloud/public-image-mirror#68]
当 镜像拉取失败，报错为 500 Internal Server Error， 通常是因为 ufile 故障导致的。

此时 比较简单的解决方法是 重启对应的容器。（需要验证）
镜像仓库不能自动恢复。

必要时需要重启docker 😓

**Comment by yankay** [comment]
是不是把 部署到 Kubernetes，配置 liveness 就可以解决了

**Comment by wzshiming** [comment]
> 是不是把 部署到 Kubernetes，配置 liveness 就可以解决了

这样现有服务器配置可能吃不消

我感觉基于 register 镜像, 构建一个新的镜像加上检查检查的逻辑出错就自己退出, 这样可能会轻量一点

**Comment by wzshiming** [comment]
https://github.com/distribution/distribution/blob/main/docs/configuration.md

```
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
```
看了下好像自身有健康检查的配置
